### ISSUE TITLE
Integrate AppVeyor CI

### ISSUE THREAD

**Issue by evpobr** [erikd/libsndfile#247]
https://www.appveyor.com/, the same thing as Travis CI, but for Windows with Visual Studio.

- [x] ~~`libflac` cannot be configured with vcpkg in x86 mode, vcpkg bug, [issue created](https://github.com/Microsoft/vcpkg/issues/988).~~ Fixed with Microsoft/vcpkg#991
- [x] `checksum_test` fails, but only in Debug mode (AppVayor test is Debug) #248
- [x]  Known bug with `misc_test_rf64` #244
- [x]  win32_ordinal_test fails

**Comment by evpobr** [comment]
@erikd, register and setup please, i will add `appveyor.yml`.

**Comment by erikd** [comment]
Done.

**Comment by evpobr** [comment]
Well, can you tell AppVeyor to test only `wip/appveyor` branch?

**Comment by erikd** [comment]
Done.

**Comment by evpobr** [comment]
Tests are done, with VS2017 x86 & x64, Xiph.org codecs are enabled.

Problems:

1. `libflac` cannot be configured with vcpkg in x86 mode, vcpkg bug, [issue created](https://github.com/Microsoft/vcpkg/issues/988)
2. `checksum_test` fails, but only in Debug mode (AppVayor test is Debug)
3. Known bug with `misc_test_rf64`

**Comment by erikd** [comment]
The `checksum_test` should be investigated. There is no good reason for it to give different results in Debug mode.

**Comment by evpobr** [comment]
Bugs are fixed, but it's better to wait a little, [Appvayor wants to incorporate Vcpkg](https://github.com/appveyor/ci/issues/1076). I hope it will speed up testing process.

**Comment by evpobr** [comment]
@erikd , feature complete. A bit faster now, since `vcpkg` is now integrated to Appveyor. Test time ~20 min (latest Travis test is ~17 min).

**Comment by frabert** [comment]
Would you consider adding artifacts to the build? This could make it easier to download the precompiled libraries to use in other projects

**Comment by evpobr** [comment]
Sorry, have no time, patches welcome. And it's always better to use package managers. For windows it could be `Vcpkg` or something else.

**Comment by evpobr** [comment]
It is working, so i close this.
